In [6]:
from kaggle_environments import make,evaluate
from utils.helper_one_stop import get_heuristic

import numpy as np

grid=np.zeros((6,7),dtype=int)
grid[5,1:4] = 1
print(grid)

config = lambda: None
config.rows = 6
config.columns = 7
config.inarow = 4


print(get_heuristic(grid,1,config))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0]]
2.0


In [15]:
grid_2=np.zeros((6,7),dtype=int)
grid_2[5,2:5] = 1
grid_2[3:6,0] = 1

print(grid_2)

config = lambda: None
config.rows = 6
config.columns = 7
config.inarow = 4

print(get_heuristic(grid_2,1,config))


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 1 1 1 0 0]]
4.0
